### ISSUE TITLE
Ready to get screenshot from session:2!

### ISSUE THREAD

**Issue by ppuuoo** [baiyies/ScreenshotBOFPlus#3]
beacon> screenshot_plus
[*] Running screenshot without injection
[+] host called home, sent: 3972 bytes
[+] received output:
Ready to get screenshot from session:2!
截图里面没有，这种就是没成功吗?目标有eset 不会被拦截了吧

**Comment by baiyies** [comment]
被拦截了，或者是因为你网络不好和profile回传设置的问题，导致还没把数据全部传回来。
